# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-07-12 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jazz', '0010_auto_20150804_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='sex',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('n', 'n/k')], default='n', max_length=1),
        ),
    ]
